-- Create table for Memes
create table if not exists memes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  author text not null,
  url text not null,
  tags text[] default '{}',
  type text default 'image',
  comments int default 0,
  date text, -- We store the formatted date string for simplicity as per current app logic
  is_meme boolean default true,
  show_on_home boolean default false
);

-- Create table for About Page Configuration
create table if not exists about_info (
  id int primary key default 1,
  data jsonb not null
);

-- Policy to allow anonymous read/write (since this is a public fun app)
-- Note: In a real production app, we would enable RLS and use proper Auth.
alter table memes enable row level security;
create policy "Public Memes Access" on memes for all using (true) with check (true);

alter table about_info enable row level security;
create policy "Public About Access" on about_info for all using (true) with check (true);

-- Insert initial About Data (ONLY RUN THIS ONCE)
insert into about_info (id, data)
values (1, '{
    "introText": [
        "Somos más que un grupo de amigos; somos una entidad digital colectiva unida por la procrastinación, los memes de dudosa calidad y las sesiones de gaming hasta el amanecer.",
        "Este sitio es nuestro archivo, nuestro patio de recreo y nuestra base de operaciones. Aquí documentamos nuestra historia, compartimos nuestros proyectos y conectamos con el mundo exterior (cuando decidimos salir de la cueva)."
    ],
    "projects": [
        {
            "id": 1,
            "title": "La Fasola Web",
            "description": "El portal digital oficial de nuestra comunidad. Un espacio para compartir memes, noticias y Caos organizado.",
            "image": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=300&h=200",
            "link": "/",
            "status": "activo"
        },
        {
            "id": 2,
            "title": "Papelina",
            "description": "Banda de Rock conformada por Marcos, Agustin, Joaquin, y Francisco.",
            "image": "https://images.unsplash.com/photo-1493225255756-d9584f8606e9?auto=format&fit=crop&q=80&w=300&h=200",
            "link": "#",
            "status": "banda"
        },
        {
            "id": 3,
            "title": "Discord Community",
            "description": "El cuartel general. Donde ocurren todas las llamadas a las 3 AM y las discusiones sobre la vida.",
            "image": "https://images.unsplash.com/photo-1614680376593-902f74cf0d41?auto=format&fit=crop&q=80&w=300&h=200",
            "status": "activo"
        }
    ],
    "network": [
        {
            "id": 1,
            "name": "Marko",
            "role": "Aspirante a Ingeniero de Software",
            "description": "Desarrollador Full Stack especializado en romper cosas y luego arreglarlas. Bajista de Papelina.",
            "image": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=200&h=200",
            "link": "https://github.com",
            "linkText": "Personal"
        },
        {
            "id": 2,
            "name": "Javier",
            "role": "Graphic Designer",
            "description": "Creativo visual. Hago que las cosas se vean bien, a diferencia de este sitio.",
            "image": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200&h=200",
            "link": "https://behance.net",
            "linkText": "Portfolio"
        },
        {
            "id": 3,
            "name": "Ana",
            "role": "Photography",
            "description": "Capturando momentos que nadie recuerda al día siguiente.",
            "image": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200&h=200",
            "link": "https://instagram.com",
            "linkText": "Gallery"
        }
    ]
}')
on conflict (id) do nothing;

-- Create table for CyberPet Stats (Global Feed/Poke/Sleep counters)
create table if not exists cyber_stats (
  id int primary key default 1,
  feed_count int default 0,
  poke_count int default 0,
  sleep_count int default 0
);

alter table cyber_stats enable row level security;
create policy "Public Stats Access" on cyber_stats for all using (true) with check (true);

insert into cyber_stats (id, feed_count, poke_count, sleep_count)
values (1, 0, 0, 0)
on conflict (id) do nothing;
